language: go
sudo: false

go:
  - 1.6

install: make all

script:
  - make cicover
  - make gotest

notifications:
  email: false

# codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
