language: go

sudo: false

go:
- 1.7

install:
  - make setup
  - make all

script:
# TODO enable when tests are fixed again - make gotest
- make projectcheck

notifications:
  email: false

branches:
  only:
    - master

after_success:
# TODO enable when tests are fixed again - bash <(curl -s https://codecov.io/bash)
