language: go

sudo: false

go:
- 1.7

install:
  - make setup
  - make all

script:
- make gotest
- make projectcheck

notifications:
  email: false

after_success:
- bash <(curl -s https://codecov.io/bash)
