coverage:
  precision: 2
  round: nearest

  status:
    project:
      default:
        target: auto
        threshold: 10
    changes:
      default: false
    patch:
      default: false

comment:
  layout: header
  behavior: new
